// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'classes': string;
  'classification': string;
}
export const cssExports: CssExports;
export default cssExports;
